### ISSUE TITLE
Static variables should be used strictly for constant values.

### ISSUE THREAD

**Issue by Polish-Civil** [buracc/RspeerTutorial#1]
https://github.com/buracc/RspeerTutorial/blob/8f595d829f73078b93dba13be81f5fe6415d1294/src/script/FirstScript.java#L23

The static variables should be used only when presenting constant values. The locations as i assume will be mutated or provided by the GUI of the script, therefore such variable should be passed on using method parameters or whatever instead making it statically available.

https://en.wikipedia.org/wiki/Dependency_injection

**Comment by buracc** [comment]
Correct, but I was going through the tutorial that was provided by Jeremy, if you go through the VOD you'll understand. I can explain these things in a future tutorial, as this one wasn't in-depth.
